# Generated by Django 4.1.6 on 2023-10-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='women',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='women',
            name='slug',
        ),
    ]
